package pakat.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import pakat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.21 14:57:33 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KortitTest {



  // Generated by ComTest BEGIN
  /** testLisaa84 */
  @Test
  public void testLisaa84() {    // Kortit: 84
    Kortit kortit = new Kortit(); 
    Kortti jace1 = new Kortti(), jace2 = new Kortti(); 
    assertEquals("From: Kortit line: 87", 0, kortit.getLkm()); 
    kortit.lisaa(jace1); assertEquals("From: Kortit line: 88", 1, kortit.getLkm()); 
    kortit.lisaa(jace2); assertEquals("From: Kortit line: 89", 2, kortit.getLkm()); 
    assertEquals("From: Kortit line: 90", jace1, kortit.anna(jace1.getID())); 
    assertEquals("From: Kortit line: 91", jace2, kortit.anna(jace2.getID())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnna125 */
  @Test
  public void testAnna125() {    // Kortit: 125
    Kortit kortit = new Kortit(); 
    Kortti kortti1 = new Kortti("Eka kortti", 1, 1); 
    Kortti kortti2 = new Kortti("Muut kortit", 2, 2); 
    kortit.lisaa(kortti1); kortit.lisaa(kortti2); 
    assertEquals("From: Kortit line: 130", kortti1, kortit.anna(kortti1.getID())); 
    assertEquals("From: Kortit line: 131", kortti2, kortit.anna(kortti2.getID())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaNimi148 */
  @Test
  public void testAnnaNimi148() {    // Kortit: 148
    Kortit kortit = new Kortit(); 
    Kortti kortti1 = new Kortti("Eka kortti", 1, 1); 
    Kortti kortti2 = new Kortti("Muut kortit", 2, 2); 
    kortit.lisaa(kortti1); kortit.lisaa(kortti2); 
    assertEquals("From: Kortit line: 153", "Eka kortti", kortit.annaNimi(kortti1.getID())); 
    assertEquals("From: Kortit line: 154", "Muut kortit", kortit.annaNimi(kortti2.getID())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString169 */
  @Test
  public void testToString169() {    // Kortit: 169
    Kortit kortit = new Kortit(); 
    Kortti kortti1 = new Kortti("Eka kortti", 1, 1); 
    Kortti kortti2 = new Kortti("Muut kortit", 2, 2); 
    kortit.lisaa(kortti1); kortit.lisaa(kortti2); 
    assertEquals("From: Kortit line: 174", "kID|kortin nimi|kpl|cmc\n1|Eka kortti|1|1\n2|Muut kortit|2|2", kortit.toString()); 
  } // Generated by ComTest END
}