package pakat.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import pakat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.23 18:41:24 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KortitTest {



  // Generated by ComTest BEGIN
  /** testLisaa86 */
  @Test
  public void testLisaa86() {    // Kortit: 86
    Kortit kortit = new Kortit(); 
    Kortti jace1 = new Kortti(), jace2 = new Kortti(); 
    assertEquals("From: Kortit line: 89", 0, kortit.getLkm()); 
    kortit.lisaa(jace1); assertEquals("From: Kortit line: 90", 1, kortit.getLkm()); 
    kortit.lisaa(jace2); assertEquals("From: Kortit line: 91", 2, kortit.getLkm()); 
    assertEquals("From: Kortit line: 92", jace1, kortit.anna(jace1.getID())); 
    assertEquals("From: Kortit line: 93", jace2, kortit.anna(jace2.getID())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnna127 */
  @Test
  public void testAnna127() {    // Kortit: 127
    Kortit kortit = new Kortit(); 
    Kortti kortti1 = new Kortti("Eka kortti", 1, 1); 
    Kortti kortti2 = new Kortti("Muut kortit", 2, 2); 
    kortit.lisaa(kortti1); kortit.lisaa(kortti2); 
    assertEquals("From: Kortit line: 132", kortti1, kortit.anna(kortti1.getID())); 
    assertEquals("From: Kortit line: 133", kortti2, kortit.anna(kortti2.getID())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaNimi186 */
  @Test
  public void testAnnaNimi186() {    // Kortit: 186
    Kortit kortit = new Kortit(); 
    Kortti kortti1 = new Kortti("Eka kortti", 1, 1); 
    Kortti kortti2 = new Kortti("Muut kortit", 2, 2); 
    kortit.lisaa(kortti1); kortit.lisaa(kortti2); 
    assertEquals("From: Kortit line: 191", "Eka kortti", kortit.annaNimi(kortti1.getID())); 
    assertEquals("From: Kortit line: 192", "Muut kortit", kortit.annaNimi(kortti2.getID())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString207 */
  @Test
  public void testToString207() {    // Kortit: 207
    Kortit kortit = new Kortit(); 
    Kortti kortti1 = new Kortti("Eka kortti", 1, 1); 
    Kortti kortti2 = new Kortti("Muut kortit", 2, 2); 
    kortit.lisaa(kortti1); kortit.lisaa(kortti2); 
    assertEquals("From: Kortit line: 212", "kID|kortin nimi|kpl|cmc\n1|Eka kortti|1|1\n2|Muut kortit|2|2", kortit.toString()); 
  } // Generated by ComTest END
}