package pakat.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import pakat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.24 11:31:23 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KorttiTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi68 */
  @Test
  public void testRekisteroi68() {    // Kortti: 68
    Kortti kortti1 = new Kortti(); 
    kortti1.rekisteroi(); 
    Kortti kortti2 = new Kortti(); 
    kortti2.rekisteroi(); 
    int n1 = kortti1.getID(); 
    int n2 = kortti2.getID(); 
    assertEquals("From: Kortti line: 75", n1+1, n2); 
  } // Generated by ComTest END
}