package pakat.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import pakat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.05 11:19:25 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class LinkitTest {



  // Generated by ComTest BEGIN
  /** testLisaa36 */
  @Test
  public void testLisaa36() {    // Linkit: 36
    Linkit linkit = new Linkit(); 
    assertEquals("From: Linkit line: 38", 0, linkit.getLkm()); 
    Linkki linkki1 = new Linkki(1,2,1,1); 
    Linkki linkki2 = new Linkki(1,3,0,2); 
    Linkki linkki3 = new Linkki(2,1,1,1); 
    Linkki linkki4 = new Linkki(2,3,2,2); 
    linkit.lisaa(linkki1); linkit.lisaa(linkki2); 
    assertEquals("From: Linkit line: 44", 2, linkit.getLkm()); 
    linkit.lisaa(linkki3); linkit.lisaa(linkki4); 
    assertEquals("From: Linkit line: 46", 4, linkit.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista84 */
  @Test
  public void testPoista84() {    // Linkit: 84
    Linkit linkit = new Linkit(); 
    Linkki linkki1 = new Linkki(1,2,1,1); 
    Linkki linkki2 = new Linkki(1,3,0,2); 
    Linkki linkki3 = new Linkki(2,1,1,1); 
    Linkki linkki4 = new Linkki(2,3,2,2); 
    linkit.lisaa(linkki1); linkit.lisaa(linkki2); 
    linkit.lisaa(linkki3); linkit.lisaa(linkki4); 
    assertEquals("From: Linkit line: 92", 4, linkit.getLkm()); 
    assertEquals("From: Linkit line: 93", linkki1, linkit.anna(1,2)); 
    linkit.poista(1,2); 
    assertEquals("From: Linkit line: 95", 3, linkit.getLkm()); 
    assertEquals("From: Linkit line: 96", null, linkit.anna(1,2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnna133 */
  @Test
  public void testAnna133() {    // Linkit: 133
    Linkit linkit = new Linkit(); 
    Linkki linkki1 = new Linkki(1,2,1,1); 
    Linkki linkki2 = new Linkki(1,3,0,2); 
    Linkki linkki3 = new Linkki(2,1,1,1); 
    Linkki linkki4 = new Linkki(2,3,2,2); 
    linkit.lisaa(linkki1); linkit.lisaa(linkki2); 
    linkit.lisaa(linkki3); linkit.lisaa(linkki4); 
    assertEquals("From: Linkit line: 141", linkki1, linkit.anna(1,2)); 
    assertEquals("From: Linkit line: 142", linkki2, linkit.anna(1,3)); 
    linkit.poista(2, 3); 
    assertEquals("From: Linkit line: 144", null, linkit.anna(2, 3)); 
  } // Generated by ComTest END
}