package pakat.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import pakat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.05 11:19:05 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class LinkkiTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi54 */
  @Test
  public void testRekisteroi54() {    // Linkki: 54
    Linkki linkki1 = new Linkki(1,2,4,4); 
    Linkki linkki2 = new Linkki(2,3,0,1); 
    int n1 = linkki1.getID(); 
    int n2 = linkki2.getID(); 
    assertEquals("From: Linkki line: 59", n1+1, n2); 
  } // Generated by ComTest END
}