package pakat.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import pakat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.05 11:18:00 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PakatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa43 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa43() throws SailoException {    // Pakat: 43
    Pakat pakat = new Pakat(); 
    Pakka izzet1 = new Pakka(), izzet2 = new Pakka(); 
    assertEquals("From: Pakat line: 47", 0+1, pakat.getLkm()); 
    pakat.lisaa(izzet1); assertEquals("From: Pakat line: 48", 1+1, pakat.getLkm()); 
    pakat.lisaa(izzet2); assertEquals("From: Pakat line: 49", 2+1, pakat.getLkm()); 
    pakat.lisaa(izzet1); assertEquals("From: Pakat line: 50", 3+1, pakat.getLkm()); 
    assertEquals("From: Pakat line: 51", izzet1, pakat.anna(0+1)); 
    assertEquals("From: Pakat line: 52", izzet2, pakat.anna(1+1)); 
    assertEquals("From: Pakat line: 53", izzet1, pakat.anna(2+1)); 
    assertEquals("From: Pakat line: 54", false, pakat.anna(1+1) == izzet1); 
    assertEquals("From: Pakat line: 55", true, pakat.anna(1+1) == izzet2); 
    try {
    assertEquals("From: Pakat line: 56", izzet1, pakat.anna(3+1)); 
    fail("Pakat: 56 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    pakat.lisaa(izzet1); assertEquals("From: Pakat line: 57", 4+1, pakat.getLkm()); 
    try {
    pakat.lisaa(izzet1); 
    fail("Pakat: 58 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}