package pakat.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import pakat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.16 12:44:59 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PakatTest {



  // Generated by ComTest BEGIN
  /** testLisaa39 */
  @Test
  public void testLisaa39() {    // Pakat: 39
    Pakat pakat = new Pakat(); 
    Pakka izzet1 = new Pakka(), izzet2 = new Pakka(); 
    assertEquals("From: Pakat line: 42", 0+1, pakat.getLkm()); 
    pakat.lisaa(izzet1); assertEquals("From: Pakat line: 43", 1+1, pakat.getLkm()); 
    pakat.lisaa(izzet2); assertEquals("From: Pakat line: 44", 2+1, pakat.getLkm()); 
    pakat.lisaa(izzet1); assertEquals("From: Pakat line: 45", 3+1, pakat.getLkm()); 
    assertEquals("From: Pakat line: 46", izzet1, pakat.anna(0+1)); 
    assertEquals("From: Pakat line: 47", izzet2, pakat.anna(1+1)); 
    assertEquals("From: Pakat line: 48", izzet1, pakat.anna(2+1)); 
    assertEquals("From: Pakat line: 49", false, pakat.anna(1+1) == izzet1); 
    assertEquals("From: Pakat line: 50", true, pakat.anna(1+1) == izzet2); 
    try {
    assertEquals("From: Pakat line: 51", izzet1, pakat.anna(3+1)); 
    fail("Pakat: 51 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    pakat.lisaa(izzet1); assertEquals("From: Pakat line: 52", 4+1, pakat.getLkm()); 
    pakat.lisaa(izzet1); assertEquals("From: Pakat line: 53", true, pakat.getLkm() > 5); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaaTilaa66 */
  @Test
  public void testLisaaTilaa66() {    // Pakat: 66
    Pakat pakat = new Pakat(); 
    assertEquals("From: Pakat line: 68", 1, pakat.getLkm()); 
    assertEquals("From: Pakat line: 69", 5, pakat.getKoko()); 
    pakat.lisaa(new Pakka()); pakat.lisaa(new Pakka()); 
    pakat.lisaa(new Pakka()); pakat.lisaa(new Pakka()); 
    pakat.lisaa(new Pakka()); assertEquals("From: Pakat line: 72", 6, pakat.getLkm()); 
    assertEquals("From: Pakat line: 73", 10, pakat.getKoko()); 
  } // Generated by ComTest END
}