package pakat.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import pakat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.21 15:04:32 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PakkaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi77 */
  @Test
  public void testRekisteroi77() {    // Pakka: 77
    Pakka pakka1 = new Pakka(); 
    pakka1.rekisteroi(); 
    Pakka pakka2 = new Pakka(); 
    pakka2.rekisteroi(); 
    int n1 = pakka1.getID(); 
    int n2 = pakka2.getID(); 
    assertEquals("From: Pakka line: 84", n1+1, n2); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString157 */
  @Test
  public void testToString157() {    // Pakka: 157
    Pakka pakka1 = new Pakka("Ekapakka", 2, "Eka"); 
    Pakka pakka2 = new Pakka("Tokapakka", 3, "Toka"); 
    pakka1.rekisteroi(); 
    pakka2.rekisteroi(); 
    assertEquals("From: Pakka line: 162", "1|Ekapakka|2|Eka", pakka1.toString()); 
    assertEquals("From: Pakka line: 163", "2|Tokapakka|3|Toka", pakka2.toString()); 
  } // Generated by ComTest END
}