package pakat.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import pakat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.05 11:13:28 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PakkaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi52 */
  @Test
  public void testRekisteroi52() {    // Pakka: 52
    Pakka pakka1 = new Pakka(); 
    pakka1.rekisteroi(); 
    Pakka pakka2 = new Pakka(); 
    pakka2.rekisteroi(); 
    int n1 = pakka1.getID(); 
    int n2 = pakka2.getID(); 
    assertEquals("From: Pakka line: 59", n1+1, n2); 
  } // Generated by ComTest END
}