package pakat.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static pakat.Tarkistus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.02 12:17:44 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TarkistusTest {



  // Generated by ComTest BEGIN
  /** testNimiTarkistus20 */
  @Test
  public void testNimiTarkistus20() {    // Tarkistus: 20
    String huonoNimi = "Snapcaster | Mage"; 
    String parempiNimi = nimiTarkistus(huonoNimi); 
    assertEquals("From: Tarkistus line: 23", "Snapcaster Mage", parempiNimi); 
    String h2 = "Snapcaster    Mage "; 
    String p2 = nimiTarkistus(h2); 
    assertEquals("From: Tarkistus line: 26", "Snapcaster Mage", p2); 
  } // Generated by ComTest END
}